version: lastet

services:
  
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: estagiocompass
    volumes:
      - ./mongodb-init/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - volume-projeto:/var/lib/postgresql/data
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: estagiocompass
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:estagiocompass@mongo:27017/
    volumes:
      - volume-projeto:/var/lib/postgresql/data

  postgres:

    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: estagiocompass
    volumes:
      - volume-projeto:/var/lib/postgresql/data
      
  python:

    build:
      dockerfile: /docker/Dockerfile
      context: ./python_etl
    depends_on:
      - postgres
      - mongo
    ports:
      - 3000:3000
    restart: always
    volumes:
      - volume-projeto:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  volume-projeto:

 